manifest:
  defaults:
    revision: v0.2
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: cobra_cadence
      url-base: https://github.com/mreel/cobra_cadence_module
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
    - name: cobra_cadence
      remote: cobra_cadence
      revision: main
  self:
    path: config
