manifest:
  defaults:
    revision: v0.2
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: mreel
      url-base: https://github.com/mreel
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
    - name: cobra_cadence_module
      remote: mreel
      revision: main
  self:
    path: config
